site_name: Howto_co34pt_LiveCode

pages:
    - About: 
        - 'Contents': 'index.md'
        - 'To-Do list': 'todo.md'
        - 'License': 'legalcode.md'
    - Introduction:
        - 'What this Repo Is': '1-1-What-This-Repo-Is.md'
        - 'Why I live Code': '1-2-Why-I-Live-Code.md'
        - 'Why SuperCollider?': '1-3-Why-SuperCollider.md'
        - 'How To Use This Repo': '1-4-How-To-Use-This-Repo.md'
    - Basics:
        - 'Recommended Addons': '2-1-Recommended-Addons.md'
        - 'ProxySpace - Live Coding in SuperCollider': '2-2-Why-ProxySpace.md'
        - 'Setup Code: Making Performance Easier': '2-3-Setup-Code---Making-Performance-Easier.md'
        - 'Pbinds and Patterns: The Basics': '2-4-Pbinds-and-Patterns.md'
    - Rhythm:
        - 'Rhythmic Construction for Algorave Sets': '3-1-Rhythmic-Construction-For-Algorave-Sets.md'
        - 'Basic Rhythms': '3-2-Basic-Rhythms.md'
        - 'Techniques for Modifying Rhythm': '3-3-Techniques-For-Modifying-Rhythm.md'
        - 'Euclidean Rhythms': '3-4-Euclidean-Rhythms.md'
        - 'StageLimiter Abuse': '3-5-StageLimiter-Abuse.md'
        - 'L-Systems for Rhythm': '3-6-L-Systems-For-Rhythm.md'
        - 'Looping and using Looped Samples': '3-7-Looping.md'
    - Melody and Pitch:
        - 'Pitch and Patterns': '4-1-Pitch-And-Patterns.md'
        - 'Types of Pitch Arrangement': '4-2-Types-of-Pitch-Arrangement.md'
        - 'Riffs': '4-3-Riffs.md'
        - 'Pitch and Static Synths': '4-4-Pitch-and-Static-Synths.md'
        - 'Between Pitch and Noise': '4-5-Between-Pitch-And-Noise.md'
        - 'Good SynthDef Writing for co34pt_LiveCode': '4-6-Good-SynthDef-Writing-for-co34pt_LiveCode.md'
        - 'Using MIDI': '4-7-MIDI.md'
    - Non-Pattern Techniques:
        - 'Drones': '5-1-Drones.md'
        - 'SuperCollider as a Modular Synth': '5-2-SuperCollider-as-a-Modular-Synth.md'
    - Visuals and Data:
        - 'FreqScope and Visuals': '6-1-FreqScope-and-Visuals.md'
        - 'OSC and Data Streams': '6-2-OSC-and-Data-Streams.md'
        - 'Using Datasets': '6-3-Using-Datasets.md'

theme: cinder
